version: 2
updates:
  # Enable version updates for root npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    labels:
      - "dependencies"
      - "npm"
      - "root"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"

  # Enable version updates for packages
  - package-ecosystem: "npm"
    directory: "/packages"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    labels:
      - "dependencies"
      - "npm"
      - "packages"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"

  # Enable version updates for apps
  - package-ecosystem: "npm"
    directory: "/apps"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    labels:
      - "dependencies"
      - "npm"
      - "apps"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
